blog_all_homepage:
    path:     /blog_all/{id}
    defaults: { _controller: BlogAllBundle:Default:index }

blog_show:
    path:     /blog_show
    defaults: { _controller: BlogAllBundle:Default:show }

add_article:
    path:     /add_article
    defaults: { _controller: BlogAllBundle:Add:article }