blog_all_article:
    resource: "@BlogAllBundle/Controller/ArticleController.php"
    type:     annotation

blog_all:
    resource: "@BlogAllBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Editor_my:
    path: /editor
    defaults: { _controller: AppBundle:Editor:create }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

call_me:
    path: /call_me
    defaults: { _controller: AppBundle:Welcome:callme }